### ISSUE TITLE
Fix Hugo Example

### ISSUE THREAD

**Issue by johnmccawley** [thedigitalgarage/hugo-ex#1]
Hugo config file in hugo example project is not working properly. It should be able to read an environment variable set for the container from the deployment config (HUGO_BASEURL) that is not working. That should set the url to the url of the APPLICATIONDOMAIN in Openshift. Currently the baseurl is defaulting to localhost which keeps the static site from accessing css and image files.

**Comment by noeldevelops** [comment]
Hugo will default the baseURL to localhost when running the `hugo server` command, but it can be overridden by adding `--baseURL=" "` flag. 

also, it appears you can leave the baseURL empty and it will default to project root 
https://discuss.gohugo.io/t/gohugo-without-baseurl-or-with-relative-url-only/2779

I will try to test this

**Comment by johnmccawley** [comment]
Hi @anc02d Noel, That is really interesting! I am not sure where the hugo server command is invoked. (the template or the builder image) I will research that. I think that it should be invoked as a post deploy hook. If that is the case, we could inject the baseurl as an evironment variable.

**Comment by johnmccawley** [comment]
Found it. In the run file of the source to image builder: https://github.com/thedigitalgarage/s2i-hugo/blob/master/s2i/run

# Start hugo server
hugo server --bind=0.0.0.0 \
  --port=8080 \
  --disableLiveReload=true \
  --watch=false \
  --appendPort=false \
  --verboseLog \
  --logFile=$pipe &

So this is why it is set to localhost. there is no base URL defined.

**Comment by noeldevelops** [comment]
I see @johnmccawley 
Checking for understanding--> the s2i run file should include a `--baseURL` flag that is set to HUGO_BASEURL (which will be grabbed from the deployment config)?

**Comment by johnmccawley** [comment]
I am not sure. There are a couple of approaches we could take. 

1. Set Hugo up so that it runs the internal Hugo web server. 
2. Have the Hugo s2i builder generate a site (https://gohugo.io/overview/quickstart/ Step 11: Generate a site) and serve it up through NGINX or Apache. 

I am not sure that is the way to go. I would think we would want to run most of the dev work for Hugo on our local machines since it does not require an integration of other services or applications in order to do the development. Also, because Hugo has the live reload feature, it is perfect for quick roundtrip dev cycles on your local machine. You would not get the benefit of the live reload on Digital Garage. After you feel comfortable with the dev work, I would then push a site to Digital Garage for hosting. I will modify the builder and template to do the same thing the Jekyll builder and template do. They take the raw source from the github repository, generate the site and then deploy the site on a NGINX web server. It is not that I do not like Hugo's web server, but NGINX is much more configurable for a production web site.

**Comment by noeldevelops** [comment]
Copy that. 
I will take a look at the Jekyll builder/template

**Comment by johnmccawley** [comment]
Hugo example and Hugo template are fixed.
